### ISSUE TITLE
Map markers not in correct location

### ISSUE THREAD

**Issue by EnKrypt** [DNSCrypt/dnscrypt-website#10]
I came across this issue while trying to search for my resolver on the map.

![](https://i.imgur.com/5Ixnnws.png)

Hovering over Bangalore, India I found it showing a resolver that I guess should be in Taiwan instead?

I also noticed `opennic-luggs2` below it in the middle of the Indian Ocean, which should be in Canada I believe. 

The markers seem be in wrong locations.

**Comment by publicarray** [comment]
Thanks, Yea the locations are gathered from an IP database. Perhaps @jedisct1 can update the database version?

**Comment by jedisct1** [comment]
Hi!

Indeed, this is just using the Geolite City database.

I just updated it, but the installed version was only 1 month old, so it may not make a big difference.

Geo IP databases are not very accurate.
