### ISSUE TITLE
Can't generate DoT stamp

### ISSUE THREAD

**Issue by anonymous1184** [DNSCrypt/dnscrypt-website#11]
Stamps page (https://dnscrypt.info/stamps/) doesn't allows to create DoT.
![img](https://user-images.githubusercontent.com/53758552/62537683-a2b3e280-b816-11e9-950f-c385f516aee2.png)

**Comment by jedisct1** [comment]
DoT is not supported by that tool, but feel free to implement it!

**Comment by ibksturm** [comment]
@jedisct1 Hi Frank :)

Hope your are fine cause of the stupid COVID-19. 

Comming back do DoT Stamp generating, here https://play.golang.org/p/fACN5hsChEG is a implementation in Go from  AdGuardHomeguy @admitrevskiy 

Sadly i'm not fit in Go and in .vue files, but maybe theres something to you :)

My wish is that on the dnscrypt.info/stamps website there will be the implementation of

- Plain DNS IPv4
- Plain DNS IPv6
- DoT

**Comment by admitrevskiy** [comment]
Hi guys!
AdGuard [DnsProxy](https://github.com/AdguardTeam/dnsproxy) and [DnsLibs](https://github.com/AdguardTeam/dnslibs) supports SDNS-proto-like syntax for plain IPv4/6 and DoT upstreams.
[This](https://play.golang.org/p/fACN5hsChEG ) is just a simple implementation to pass minimum necessary upstreams info to AdGuard products.

It would be great if dnscrypt.info/stamps website enabled support for DoT and plain DNS.

**Comment by anonymous1184** [comment]
Ty @ibksturm!

For the folks (like me), that for NO SPECIFIC reason like more the DoT over DoH this is great. Everytime I'm forced out of DNSCrypt I go over TLS. At this point in this dummy battle is useless present arguments (I'm still in the battle over spaces vs tabs since the 90s).

**Comment by ibksturm** [comment]
>  (I'm still in the battle over spaces vs tabs since the 90s).

cool :) didn‘t know there was even a battle about spaces and tabs. and yeah, i‘m not that second young ^^
