### ISSUE TITLE
dnscrypt.org?

### ISSUE THREAD

**Issue by ledlamp** [DNSCrypt/dnscrypt-website#12]
There's dnscrypt.info and dnscrypt.org... is dnscrypt.org legitimate? Why are there two official sites?

**Comment by jedisct1** [comment]
Not legit.

I have no idea who is behind this. They illegally copied a version of the website from 2017 (from archive.org probably), and at some point, redirected to a Chinese website to download the code.

There are shady files with `dnscrypt` in their name on torrents and forums as well.

Stay away from these unless you want malware.

The only official websites are dnscrypt.info and what's in GitHub in the dnscrypt organization.

**Comment by ledlamp** [comment]
Well dang! That site came up first on Bing and this site second; I actually thought it was the official one and dnscrypt.info was a phony because of the TLDs and the way they looked... but then found the GitHub org and was confused to see that the other one is actually legit. Damn that sucks, for a phony site to get a better TLD _and_ search engine rankings D:
