### ISSUE TITLE
Plain DNS stamp

### ISSUE THREAD

**Issue by black-cerberon** [DNSCrypt/dnscrypt-website#13]
Can't choose plain DNS in stamp generator.

**Comment by jedisct1** [comment]
Well, this is expected, as this has never been implemented.

What software supports DNS stamps and plain DNS?

**Comment by black-cerberon** [comment]
I just found info about plain DNS stamp in [docs](https://dnscrypt.info/stamps-specifications/), but generator doesn't have it.

**Comment by black-cerberon** [comment]
How I can you plain DNS with `dnscrypt-proxy`?

**Comment by jedisct1** [comment]
`dnscrypt-proxy` only supports encrypted DNS servers.
