### ISSUE TITLE
IPv6 support

### ISSUE THREAD

**Issue by marzzzello** [DNSCrypt/dnscrypt-website#16]
AAAA records are missing for dnscrypt.info
Sadly GitHub doesn't support IPv6 so it would be really helpful to have the public resolvers list on a server that is reachable via IPv6.

**Comment by marzzzello** [comment]
@jedisct1 why was this issue closed?

**Comment by jedisct1** [comment]
Because it is available at `https://ipv6.download.dnscrypt.info` and `https://download.dnscrypt.net`.

**Comment by marzzzello** [comment]
Ah good to know. Thanks!

**Comment by illiliti** [comment]
@jedisct1 Is there a way to get specification copy of dnscrypt(and stamps) if i have only ipv6 connection? Neither dnscrypt.info nor github support ipv6, hence this question.
