### ISSUE TITLE
DNSCrypt logo in SVG

### ISSUE THREAD

**Issue by yegortimoshenko** [DNSCrypt/dnscrypt-website#2]
Hi, is there a SVG version of DNSCrypt logo? I would like it for nylira/prism-break#2003.

**Comment by publicarray** [comment]
Hi @yegortimoshenko, 
I am a fan of prism break project.
As far as I'm aware there is no SVG version of the logo available. However It is possible that @jedisct1 might know more.

**Comment by publicarray** [comment]
Duplicate of https://github.com/jedisct1/dnscrypt-proxy/issues/523
