### ISSUE TITLE
dnscrypt.info/stamps lists DoH as "DNS over HTTP" instead of HTTPS

### ISSUE THREAD

**Issue by bsmith7581** [DNSCrypt/dnscrypt-website#24]
Listing DoH as "DNS over HTTP" could lead people to believe it's using unencrypted HTTP instead of HTTPS.  I found the source of the error. It is in components/DNSStamp.vue. 

![dnscrypt-stamps-DoH](https://user-images.githubusercontent.com/11051993/128639877-8c82150d-7eac-42c6-ac38-086484b4b5ef.png)

**Comment by jedisct1** [comment]
Fixed, thank you! 👍
