### ISSUE TITLE
Port in DNS-over-HTTPS stamps

### ISSUE THREAD

**Issue by taam** [DNSCrypt/dnscrypt-website#25]
The DNS Stamps specification is not quite clear regarding where to put the port. For the stamps currently in use, the port seems to be always in the `hostname` field, which I think is in violation of the specification as currently written (the port is certainly not part of the SNI name). Also given the description of the `addr` field, it seems it would be more consistent to put it there. I think this should be clarified. Thanks!

**Comment by jedisct1** [comment]
Thanks for pointing this out!

Having the port in the `addr` field would indeed make sense and be consistent with the DNSCrypt protocol.

However, implementations assume it to be in the hostname field, so the specification was updated accordingly.

Thanks again!
