### ISSUE TITLE
Wrong http CSP(Content-Security-Policy) header?

### ISSUE THREAD

**Issue by PeterDaveHello** [DNSCrypt/dnscrypt-website#26]
Just found that there's an error of the CSP header, and looks like the directive is missing, something like `default-src` should be added.

I can't find the place to send a PR for it, so an issue's here instead.

![image](https://user-images.githubusercontent.com/3691490/146877433-3aef80c1-1c12-4335-9456-225d36d3f5b2.png)

```sh
$ curl -sI https://dnscrypt.info/stamps/ | grep -i ^content-security-policy
content-security-policy: https: 'unsafe-inline'; reflected-xss block
```

https://csp-evaluator.withgoogle.com/

![image](https://user-images.githubusercontent.com/3691490/146878227-b7298325-4b2a-4c4a-9a57-352071289f98.png)

**Comment by jedisct1** [comment]
Thanks!

The CSP has been updated.
