### ISSUE TITLE
DNSCrypt stamps: fix typo

### ISSUE THREAD

**Issue by dl9sau** [DNSCrypt/dnscrypt-website#8]
In the description of "DNSCrypt stamps"
at https://github.com/DNSCrypt/dnscrypt-website/blob/master/pages/stamps-specifications.vue
at the line:
  "sdns://" || base64url(0x01 || props || LP(addr) || LP(pk || LP(providerName))
..we see a missing ')' behind "LP(pk". Thought first it would be LP(PK || LP(providerName)).

-> please fix the doku to
  "sdns://" || base64url(0x01 || props || LP(addr) || LP(pk) || LP(providerName))

**Comment by jedisct1** [comment]
Good catch, thanks!
